<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    // just examples how to allow mass assignment to some / all properties
    //protected $fillable = ['title', 'slug', 'body', 'excerpt'];
    protected $guarded = ['id']; // make only id not mass assignable

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function category()
    {
        // possible: hasOne, hasMany, belongsTo, belongsToMany
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        // possible: hasOne, hasMany, belongsTo, belongsToMany
        return $this->belongsTo(User::class);
    }

    // this way we can refer to the autor as Post->author, note the second
    // argument in belongsTo
    public function author()
    {
        // possible: hasOne, hasMany, belongsTo, belongsToMany
        return $this->belongsTo(User::class, 'user_id');
    }
}
